# Construction of metacells (for 'continuous' data) {#MC-continuous}

```{r include=FALSE}
source('./R/config.R')
```


```{python true-import, echo = FALSE, result = FALSE, message = FALSE, warning = FALSE}
# This is true import section that is executed, but not displayed as it simultaneously load MC2 and SEACells.
# As MC2 and SEACells workflow displayed in separate files, while indeed they run in the same file/session (due to fact that in bookdown one and only one chapter per Rmd file)
# The following import chunks, specific to SEACells and MC2 are not executed, although displayed for users. 

import os
import numpy as np
import pandas as pd
import anndata as ad
import scanpy as sc
import matplotlib.pyplot as plt
import seaborn as sns
import metacells as mc
import SEACells
import random 

import sys
sys.path.append('./mc_QC/') 
import mc_QC
```


## MC2 (Python)

```{r, child = './sub_pages/31-mc2.Rmd'}

```


## SuperCell (R)


```{r, child='./sub_pages/31-supercell.Rmd'}

```



## SEACells (Python)

```{r child='./sub_pages/31-seacells.Rmd'}

```